### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by LennardF1989** [Roderik11/Squid#1]
Just a note of appreciation for open-sourcing this! I e-mailed you some time back about when this was going to happen. I forked your repository and will be pushing things to you as I encounter them.

I have been using a decompiled version so far and made a few adjustments that are already worth-while to push back in the short future, most notable: Rotation with working collision (currently a desktop as a whole, since that's what I needed).

**Comment by Roderik11** [comment]
You are very welcome and thank you!
Also that sounds really cool.

2016-04-27 16:01 GMT+02:00, Lennard Fonteijn notifications@github.com:
