### ISSUE TITLE
How does TextWrap works?

### ISSUE THREAD

**Issue by galvesribeiro** [Roderik11/Squid#3]
Hi!

I have the following code that is used in a message screen:

```
_msgFrame = new Frame();
            _msgFrame.Dock = DockStyle.Bottom;

            _msgFrame.Size = new Point(240, 280);
            Controls.Add(_msgFrame);

            _lblMsg = new Label();
            _lblMsg.Dock = DockStyle.Fill;
            _lblMsg.TextWrap = true;
            _lblMsg.Style = textStyle;
            _lblMsg.Text = message;
            _lblMsg.Margin = new Margin(10);
            _msgFrame.Controls.Add(_lblMsg);
```

So, how does the `Label.TextWrap` works? I would expect that set it to true would make a word which will cross the right border of the control to be wrapped to the next line but that isn't happening...

Am I doing anything wrong?

Thanks again for the great framework! :)

**Comment by Donaut** [comment]
Hi.

Squid can't break very long words to new lines.
