### ISSUE TITLE
How to properly close Window?

### ISSUE THREAD

**Issue by galvesribeiro** [Roderik11/Squid#4]
@Roderik11 

After we can `window.Show(desktop)` how can we close a window and stop it to being invoked on the render loop?

We noticed that after we call window.Close() the window still receive calls on DrawBefore() and DrawCustom()

How do make it stop rendering?

Thanks

**Comment by galvesribeiro** [comment]
@Roderik11  ?

**Comment by Roderik11** [comment]
I am unable to reproduce this. Could you give me some code context please.
