### ISSUE TITLE
some problems with the source code 

### ISSUE THREAD

**Issue by sgf** [Roderik11/Squid#6]
all of  .dds files not include in the source code
no input
![image](https://github.com/Roderik11/Squid/assets/2557696/2ba82531-327e-4d69-a13a-3afc64e940f2)
 GenerateStandardSkin looks not good desktop.Skin = Gui.GenerateStandardSkin();

![image](https://github.com/Roderik11/Squid/assets/2557696/c981bc95-2f48-4662-b1da-efe462485c99)

**Comment by Roderik11** [comment]
The sample code is just an example. Squid does not provide any input layer, render loop, etc.
It's purely a GUI blackbox - you need to implement input polling and rendering yourself.
VirtualKeyToScanCode can be implemented using the Win32 API.

Regarding the default skin i guess can i upload the dds files - i'll look into it.
But also highly encourage you to create  your own skin, so you get a better understanding of it all.
Cheers!

**Comment by sgf** [comment]
Maybe dds is not necessary, and a skin similar to imgui can be built. In other words, all skins are drawn by code without any texture involvement.

**Comment by Roderik11** [comment]
Yes you can easily create a skin without textures. All you need is a single white texture and a font.
In fact that's what i usually do in my own projects.

**Comment by Roderik11** [comment]
> Maybe dds is not necessary, and a skin similar to imgui can be built. In other words, all skins are drawn by code without any texture involvement.

Having read this a second time i now understand you probably mean the Squid standard skin should not reference any textures.
That makes a lot of sense to me. I'll look into this. In the meantime i have uploaded all resources referenced in the standard skin.
